import {
  Droplets, Wind, Layers, Brush, Shield, TreePine,
  Scissors, Wrench, Hammer, FlaskConical, Palette,
  Flame, Grid3x3, Droplet, Waves,
} from 'lucide-react';
import type { LucideProps } from 'lucide-react';
import type { FC } from 'react';

export const CATEGORY_ICONS: Record<string, FC<LucideProps>> = {
  'germetyky':          Droplets,
  'sylikonovi-germetyky': Droplets,
  'akrylovi-germetyky': Droplets,
  'poliuretanovi-germetyky': Droplets,
  'bitumni-germetyky':  Droplets,
  'ms-polymerni-hermetyky': Droplets,
  'montazhna-pina':     Wind,
  'pistoletna-pina':    Wind,
  'pobutova-pina':      Wind,
  'vohnezakhysna-pina': Flame,
  'klei':               Layers,
  'kley':               Layers,
  'montazhnyi-klei':    Layers,
  'klei-dlya-plytky':   Layers,
  'pva-ta-stolyarnyi':  Layers,
  'epoksydni-klei':     FlaskConical,
  'grunty':             Brush,
  'gruntivky':          Brush,
  'gruntivky-gotovi':   Brush,
  'betonokontakt':      Brush,
  'antygrybok':         Shield,
  'shpaklivky':         Brush,
  'vologopoglinachi':   Droplet,
  'hidroizolyatsiya':   Waves,
  'hidroizolyatsiyni-mastyky': Waves,
  'bitumni-mastyky':    Waves,
  'praimery':           Brush,
  'zakhyst-derevyny':   TreePine,
  'antyseptyki':        TreePine,
  'morylky':            TreePine,
  'zakhysni-pokryttya': TreePine,
  'strichky':           Scissors,
  'malyarna-strichka':  Scissors,
  'hermetyzuyucha-strichka': Scissors,
  'zvukoizolyatsiyna-strichka': Scissors,
  'kriplennya':         Wrench,
  'zamazky-dlya-shviv': Grid3x3,
  'zamazky-tsementni':  Grid3x3,
  'zamazky-epoksydni':  Grid3x3,
  'plastyfikatory':     FlaskConical,
  'instrumenty':        Hammer,
  'pistolety':          Hammer,
  'rozchynnyky':        Flame,
  'farby':                  Palette,
  'alkidni-farby':          Palette,
  'farby-dlya-radiatoriv':  Palette,
};

/* Фірмовий акцент товарної родини — приглушені відтінки близької насиченості
   й світлоти, щоб поруч у сайдбарі нічого не «кричало». Підкатегорії
   успадковують колір родини. Ключі ті самі, що в CATEGORY_ICONS. */
export const CATEGORY_COLORS: Record<string, string> = {
  'germetyky':          '#4880B8',
  'sylikonovi-germetyky': '#4880B8',
  'akrylovi-germetyky': '#4880B8',
  'poliuretanovi-germetyky': '#4880B8',
  'bitumni-germetyky':  '#4880B8',
  'ms-polymerni-hermetyky': '#4880B8',
  'montazhna-pina':     '#7B8CC8',
  'pistoletna-pina':    '#7B8CC8',
  'pobutova-pina':      '#7B8CC8',
  'vohnezakhysna-pina': '#C06A45',
  'klei':               '#B08540',
  'kley':               '#B08540',
  'montazhnyi-klei':    '#B08540',
  'klei-dlya-plytky':   '#B08540',
  'pva-ta-stolyarnyi':  '#B08540',
  'epoksydni-klei':     '#8467B8',
  'grunty':             '#B77748',
  'gruntivky':          '#B77748',
  'gruntivky-gotovi':   '#B77748',
  'betonokontakt':      '#B77748',
  'antygrybok':         '#4E9E68',
  'shpaklivky':         '#B77748',
  'vologopoglinachi':   '#45A5B8',
  'hidroizolyatsiya':   '#35809E',
  'hidroizolyatsiyni-mastyky': '#35809E',
  'bitumni-mastyky':    '#35809E',
  'praimery':           '#B77748',
  'zakhyst-derevyny':   '#5F9150',
  'antyseptyki':        '#5F9150',
  'morylky':            '#5F9150',
  'zakhysni-pokryttya': '#5F9150',
  'strichky':           '#C68A3E',
  'malyarna-strichka':  '#C68A3E',
  'hermetyzuyucha-strichka': '#C68A3E',
  'zvukoizolyatsiyna-strichka': '#C68A3E',
  'kriplennya':         '#7183A0',
  'zamazky-dlya-shviv': '#94806B',
  'zamazky-tsementni':  '#94806B',
  'zamazky-epoksydni':  '#94806B',
  'plastyfikatory':     '#8467B8',
  'instrumenty':        '#5E7287',
  'pistolety':          '#5E7287',
  'rozchynnyky':        '#C06A45',
  'farby':                  '#B25E93',
  'alkidni-farby':          '#B25E93',
  'farby-dlya-radiatoriv':  '#B25E93',
};

