import {
  Droplets, Wind, Layers, Brush, Shield, TreePine,
  Scissors, Wrench, Hammer, FlaskConical, Palette,
  Flame, Grid3x3, Droplet, Waves,
} from 'lucide-react';
import type { LucideProps } from 'lucide-react';
import type { FC } from 'react';

export const CATEGORY_ICONS: Record<string, FC<LucideProps>> = {
  'germetyky':          Droplets,
  'sylikonovi-germetyky': Droplets,
  'akrylovi-germetyky': Droplets,
  'poliuretanovi-germetyky': Droplets,
  'bitumni-germetyky':  Droplets,
  'ms-polymerni-hermetyky': Droplets,
  'montazhna-pina':     Wind,
  'pistoletna-pina':    Wind,
  'pobutova-pina':      Wind,
  'vohnezakhysna-pina': Flame,
  'klei':               Layers,
  'kley':               Layers,
  'montazhnyi-klei':    Layers,
  'klei-dlya-plytky':   Layers,
  'pva-ta-stolyarnyi':  Layers,
  'epoksydni-klei':     FlaskConical,
  'grunty':             Brush,
  'gruntivky':          Brush,
  'gruntivky-gotovi':   Brush,
  'betonokontakt':      Brush,
  'antygrybok':         Shield,
  'shpaklivky':         Brush,
  'vologopoglinachi':   Droplet,
  'hidroizolyatsiya':   Waves,
  'hidroizolyatsiyni-mastyky': Waves,
  'bitumni-mastyky':    Waves,
  'praimery':           Brush,
  'zakhyst-derevyny':   TreePine,
  'antyseptyki':        TreePine,
  'morylky':            TreePine,
  'zakhysni-pokryttya': TreePine,
  'strichky':           Scissors,
  'malyarna-strichka':  Scissors,
  'hermetyzuyucha-strichka': Scissors,
  'zvukoizolyatsiyna-strichka': Scissors,
  'kriplennya':         Wrench,
  'zamazky-dlya-shviv': Grid3x3,
  'zamazky-tsementni':  Grid3x3,
  'zamazky-epoksydni':  Grid3x3,
  'plastyfikatory':     FlaskConical,
  'instrumenty':        Hammer,
  'pistolety':          Hammer,
  'rozchynnyky':        Flame,
  'farby':                  Palette,
  'alkidni-farby':          Palette,
  'farby-dlya-radiatoriv':  Palette,
};

